### ISSUE TITLE
Input training data

### ISSUE THREAD

**Issue by Thomas-Frew** [Yaotian-Liu/FactorVAE#2]
Good morning!

I am having an issue with providing data for the dataset generator. What format should the data be in, and what files will I need to do this? I am excited to be able to reproduce the results from the paper.

Thank you!

**Comment by ytliu74** [comment]
To get started, you will need to convert your CSV file into a qlib supported dataset. You can find instructions on how to do this in the qlib official manual. Once you have done that, you can use [this file](https://github.com/ytliu74/FactorVAE/blob/main/generate_dataset.ipynb) as a reference for generating Alpha158 features.

I have provided a CSI folder containing some CSV files which you can try using initially. Once you are familiar with the data transfer process, feel free to use your own data.
